# Generated by Django 5.1.4 on 2026-06-03 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="file name"),
                ),
                (
                    "file_key",
                    models.CharField(
                        help_text="S3 object key or local relative path",
                        max_length=500,
                        verbose_name="file key",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="file size (bytes)"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="content type"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["task"], name="attachment_task_idx")],
            },
        ),
    ]
