# Generated by Django 5.1.4 on 2026-07-03 12:07
#
# Operation order is hand-arranged: the assignees M2M is added and existing
# single-assignee rows are copied into it BEFORE the old FK column is dropped,
# so no assignment data is lost.

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def copy_assignee_to_assignees(apps, schema_editor):
    """Copy each task's single assignee FK into the new assignees M2M."""
    Task = apps.get_model("tasks", "Task")
    Through = Task.assignees.through
    links = [
        Through(task_id=task_id, user_id=user_id)
        for task_id, user_id in (
            Task.objects.exclude(assignee_id=None).values_list("id", "assignee_id")
        )
    ]
    Through.objects.bulk_create(links, ignore_conflicts=True)


def copy_assignees_to_assignee(apps, schema_editor):
    """Reverse: restore the first (earliest-added) assignee into the FK."""
    Task = apps.get_model("tasks", "Task")
    Through = Task.assignees.through
    first_per_task = {}
    for task_id, user_id in Through.objects.order_by("id").values_list("task_id", "user_id"):
        first_per_task.setdefault(task_id, user_id)
    for task_id, user_id in first_per_task.items():
        Task.objects.filter(pk=task_id).update(assignee_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_phase3_notifications_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── New Project planning fields ───────────────────────────────────
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="due date"),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
                verbose_name="priority",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progress_override",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Manually pinned progress (0–100). When null, progress is computed from the share of tasks sitting in a terminal status column.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="progress override",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="planning",
                max_length=20,
                verbose_name="status",
            ),
        ),
        # ── New Task fields ───────────────────────────────────────────────
        migrations.AddField(
            model_name="task",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Manual completion indicator (0–100) shown on cards while the task sits in a non-terminal column.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="progress percent",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        # ── TaskStatus terminal flag ──────────────────────────────────────
        migrations.AddField(
            model_name="taskstatus",
            name="is_terminal",
            field=models.BooleanField(
                default=False,
                help_text="Tasks in this column count as completed for project progress and velocity analytics (e.g. a 'Done' column).",
                verbose_name="terminal",
            ),
        ),
        # ── assignee FK → assignees M2M (add, copy data, then drop) ──────
        migrations.AddField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignees",
            ),
        ),
        migrations.RunPython(copy_assignee_to_assignees, copy_assignees_to_assignee),
        migrations.RemoveIndex(
            model_name="task",
            name="task_assignee_idx",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
    ]
