# Generated by Django 5.1.4 on 2026-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External avatar URL (e.g. a Gravatar/pravatar link). Takes precedence over the uploaded avatar file when set.",
                verbose_name="avatar URL",
            ),
        ),
    ]
