# Generated by Django 5.1.4 on 2026-06-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="current_period_end",
            field=models.DateTimeField(
                blank=True,
                help_text="Stripe subscription period end — null for free plan.",
                null=True,
                verbose_name="current period end",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("trialing", "Trialing"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("incomplete", "Incomplete"),
                ],
                db_index=True,
                default="",
                max_length=20,
                verbose_name="subscription status",
            ),
        ),
    ]
